CaracasFruits/Controllers/SalesController.cs
using DAL.Models;
using DAL.Repositories;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaracasFruits.Controllers
{
    public class SalesController : Controller
    {
        private ISaleRepository _repository;

        public SalesController(ISaleRepository repository)
        {
            _repository = repository;
        }

        // GET: Sales
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public string _ProcessSale(string saleItems)
        {
            try
            {
                var salestemsModel = JsonConvert.DeserializeObject<List<SaleItem>>(saleItems);
                var sale = new Sale();
                sale.SaleItems = salestemsModel;
                _repository.Create(sale);
                return "The sale was processed with a total amount of $" + salestemsModel.Sum(s => s.Total) + ". You can review the sale at the report dashboard";
            }
            catch (JsonReaderException e)
            {
                return "The quantity must be a whole number";
            }
            catch(Exception e)
            {
                return "There has been a problem saving the data, please try again";
            }            
        }

        public ActionResult Report()
        {
           
            return View();
        }

        public ActionResult _Report(string from, string to)
        {
            var fromDate = DateTime.Parse(from);
            var toDate = DateTime.Parse(to);
            var dto = _repository.GetSalesByDate(fromDate, toDate);
            return PartialView("_ReportData", dto);
        }
    }
}

CaracasFruits/Views/Sales/New.cshtml
<div>
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Sales <small>New</small>
            </h1>
        </div>
    </div>
</div>
<div id="errorMessage" class="alert alert-danger" role="alert" hidden></div>
<div id="sucessMessage" class="alert alert-success" role="alert" hidden></div>
<div>
    <table id="packagesTable" class="table table-bordered">
        <thead>
            <tr>
                <th>Fruit</th>
                <th>Unit Price</th>
                <th>Quantity</th>
                <th>Total</th>
                <th></th>
            </tr>
        </thead>
        <tbody data-bind="foreach: SalesItems">
            <tr>
                <td>
                    <select class="fruitSelect form-control" data-bind="options: $root.AvailableFruits, optionsText: 'Name',
                                           value: FruitId, optionsValue:'Id'"></select>
                </td>
                <td>
                    <input type="number" step="0.01" data-bind="value: UnitPrice" class="package form-control" />
                </td>
                <td>
                    <input type="number" data-bind="value: Quantity" class="package form-control" />
                </td>
                <td><input data-bind="value: Total" class="package form-control" disabled /></td>
                <td>
                    <img data-bind="click: $root.DeleteItem" width="25" height="25" src="~/Content/Images/removeIcon.png" />
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">
                    <div style="text-align:left">
                        <strong>Grand Total</strong>
                    </div>
                </td>
                <td>
                    <div style="text-align:right">
                        <strong><span data-bind="text: QuantityTotal"></span></strong>
                    </div>
                </td>
                <td>
                    <div style="text-align:right">
                        <strong><span data-bind="text: GrandTotal"></span></strong>
                    </div>
                </td>
                <td>
                    <img data-bind="click: AddItem" width="25" height="25" src="~/Content/Images/addIcon.png" />
                </td>
            </tr>
        </tfoot>
    </table>
</div>
<br />
<hr />
<div>
    <br />
    <button id="buttonProcess" data-bind="click: ProcessSale" class="btn btn-primary" type="button">Process Sale</button>
    <a href="/Home/Index" class="btn btn-default">Back</a>
    <img data-bind="visible: Searching" width="25" height="25" src="~/Content/Images/loading.gif" />
</div>

<script type="text/javascript">
    $(document).ready(function () {
        console.log('ready!');

        // Activates knockout.js
        var SalesHub = new SalesHub();
        ko.applyBindings(SalesHub);
        SalesHub.SalesItems.push(new SalesItem());

        GetFruitsAvailable();
        function GetFruitsAvailable() {
            $.ajax({
                url: '/Fruits/_GetFruits',
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    SalesHub.AvailableFruits(data);
                    console.log(data);
                },
                error: function () {

                },
            });
        }

        //Main ViewModel
        function SalesHub() {
            var self = this;
            self.SalesItems = ko.observableArray();
            self.Searching = ko.observable(false);
            self.AvailableFruits = ko.observableArray();
            self.QuantityTotal = ko.computed(function () {
                var total = 0;
                for (var p = 0; p < self.SalesItems().length; ++p) {
                    total += parseInt(self.SalesItems()[p].Quantity());
                }
                return total;
            });
            self.GrandTotal = ko.computed(function () {
                var total = 0;
                for (var p = 0; p < self.SalesItems().length; ++p) {
                    total = parseFloat(parseFloat(total) + parseFloat(self.SalesItems()[p].Total())).toFixed(2);
                }
                return total;
            });

            self.AddItem = function () {
                self.SalesItems.push(new SalesItem());
            }

            self.DeleteItem = function (item) {
                if (self.SalesItems().length > 1) {
                    self.SalesItems.remove(item);
                }
            }

            self.ProcessSale = function () {
                $('#errorMessage').hide();
                $('#sucessMessage').hide();
                var json = ko.toJSON(self.SalesItems());
                self.Searching(true);
                $.ajax({
                    url: '/Sales/_ProcessSale',
                    type: 'POST',
                    data: { 'saleItems': json },
                    success: function (data) {
                        self.Searching(false);
                        $('#sucessMessage').show();
                        $('#sucessMessage').html(data);
                        self.SalesItems.removeAll();
                        self.SalesItems.push(new SalesItem());
                    },
                    error: function (request, status, error) {
                        console.log(request.responseText);
                        $('#errorMessage').show();
                        $('#errorMessage').html(request.responseText);
                        self.Searching(false);
                    }
                });
            }
        }

        //ViewModel
        function SalesItem() {
            var self = this;
            self.UnitPrice = ko.observable(0);
            self.Quantity = ko.observable(0);
            self.Total = ko.computed(function () {
                return parseFloat(self.UnitPrice() * parseInt(self.Quantity())).toFixed(2);
            }, self);
            self.FruitId = ko.observable();
        }
    });
</script>

CaracasFruits/Views/Sales/Report.cshtml
<div>
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Sales <small>Report</small>
            </h1>
        </div>
    </div>
</div>
<div>
    <div class="row">
        <div class="col-lg-3">
            From:
            <input id="fromDate" type='text' class="form-control"  />
        </div>
        <div class="col-lg-4">
            To:
            <input id="toDate" type='text' class="form-control" />
        </div>
        <div class="col-lg-4" style="padding-top:20px">
            <button id="buttonProcess" class="btn btn-primary" type="button">GetReport</button>
            <a href="/Home/Index" class="btn btn-default">Back</a>
            <img id="loading" src="~/Content/Images/loading.gif" width="20" height="20" hidden/>
        </div>
    </div>
    <hr />
    <div id="reportData">

    </div>
</div>
<script>
    $(document).ready(function () {        
        $('#fromDate').datetimepicker({ format: 'MM/DD/YYYY' });
        $('#toDate').datetimepicker({ format: 'MM/DD/YYYY', useCurrent: false });

        $("#fromDate").on("dp.change", function (e) {
            $('#toDate').data("DateTimePicker").minDate(e.date);
        });
        $("#toDate").on("dp.change", function (e) {
            $('#fromDate').data("DateTimePicker").maxDate(e.date);
        });

        $('#buttonProcess').click(function () {
            $('#loading').show();
            var from = $('#fromDate').val();
            var to = $('#toDate').val();
            if (from.length > 0 && to.length > 0) {
                $("#reportData").load('@(Url.Action("_Report", "Sales",null, Request.Url.Scheme))?from=' + from + '&to=' + to);
            }
            else {
                alert('Please check the values');
            }
        })
    })
</script>

CaracasFruits/Views/Sales/_ReportData.cshtml
@model IList<DAL.DTOs.FruitSale>
<div class="row">
    <div class="col-lg-6">
        @if (Model.Count > 0)
        {
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>
                            Fruit
                        </th>
                        <th>
                            Total Quanity
                        </th>
                        <th>
                            Total Amount
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                {
                        <tr>
                            <td>@item.FruitName</td>
                            <td>@item.TotalQuantity</td>
                            <td>@item.TotalAmount</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div style="text-align:center">There's no data for the selected range.</div>
        }
    </div>
    <div class="col-lg-6">
        <div>
            <canvas id="salesChart" width="200" height="200"></canvas>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#loading').hide();
        var fruits = @Html.Raw(Json.Encode(Model.Select(f => f.FruitName)));
        var sales = @Html.Raw(Json.Encode(Model.Select(f => f.TotalAmount)));
        var ctx = document.getElementById("salesChart").getContext("2d");
        var salesChart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: fruits,
                datasets: [
                    {
                        label: "",
                        backgroundColor: [
                            'rgb(102, 204, 255)',
                            'rgb(204, 204, 255)',
                            'rgb(255, 153, 204)',
                            'rgb(255, 204, 102)',
                            'rgb(102, 255, 51)',
                        ],
                        borderColor: [
                            'rgb(102, 204, 255)',
                            'rgb(204, 204, 255)',
                            'rgb(255, 153, 204)',
                            'rgb(255, 204, 102)',
                            'rgb(102, 255, 51)',
                        ],
                        borderWidth: 1,
                        data: sales
                    }
                ]
            },
            options: {
                maintainAspectRatio: false,
                legend: {
                    display: true
                }
            }
        });
    });
</script>